spring:
  datasource:
    # Mysql DB 접속
#        url: jdbc:mysql://localhost:3306/kakaoUser
#        username: root
#        password: shinsangWOO!@#
#        driver-class-name: com.mysql.cj.jdbc.Driver

    # h2 DB 접속
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always